# -*- coding: utf-8 -*-
"""TRABALHO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-HS53XsIKfdDoS2U98R7RyS_oSg__qS
"""

import gymnasium as gym
from stable_baselines3 import DQN
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, confusion_matrix, f1_score

# 1️⃣ Criar o ambiente
env = gym.make("Taxi-v3", render_mode="ansi")

# 2️⃣ Coletar dataset de experiências aleatórias
dataset = []
state, info = env.reset()
state = int(state)
done = False

while not done:
    action = env.action_space.sample()
    next_state, reward, terminated, truncated, info = env.step(action)
    next_state = int(next_state)

    dataset.append((state, action, reward, next_state, terminated))
    state = next_state
    done = terminated or truncated

print(f"Dataset coletado com {len(dataset)} experiências.\n")

# 3️⃣ Treinar agente RL usando DQN
model = DQN("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10000)

# 4️⃣ Testar agente treinado e coletar métricas
num_episodes = 5
all_rewards = []
all_steps = []

# Para métricas de predição de ações
y_true = []  # ações do dataset
y_pred = []  # ações do agente

print("🚖 Testando agente treinado...\n")

for ep in range(num_episodes):
    state, _ = env.reset()
    state = int(state)
    done = False
    total_reward = 0
    steps = 0

    while not done:
        # Escolher ação do agente
        action, _ = model.predict(state)
        next_state, reward, terminated, truncated, info = env.step(int(action))

        # Para métricas
        # Como não temos "ótimo", vamos comparar com uma ação aleatória do dataset
        y_true.append(np.random.choice([a for s, a, r, ns, t in dataset]))
        y_pred.append(int(action))

        state = int(next_state)
        total_reward += reward
        steps += 1
        done = terminated or truncated

    all_rewards.append(total_reward)
    all_steps.append(steps)
    print(f"✅ Episódio {ep+1} finalizado: Recompensa = {total_reward}, Passos = {steps}")

# 5️⃣ Estatísticas gerais
print("\n📊 Métricas gerais do teste:")
print(f"Média de recompensas: {np.mean(all_rewards):.2f}")
print(f"Desvio padrão das recompensas: {np.std(all_rewards):.2f}")
print(f"Média de passos por episódio: {np.mean(all_steps):.2f}")
print(f"Desvio padrão dos passos: {np.std(all_steps):.2f}")

# 6️⃣ Métricas de predição de ação
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)
cm = confusion_matrix(y_true, y_pred)
f1 = f1_score(y_true, y_pred, average='macro')  # média macro para várias classes

print("\n📊 Métricas de predição de ação:")
print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"F1-score (macro): {f1:.2f}")
print(f"Matriz de confusão:\n{cm}")

env.close()
print("✅ Teste finalizado.")